apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres-config
  namespace: tarea-clase7
data:
  POSTGRES_DB: mibasedatos
  PGDATA: /var/lib/postgresql/data/pgdata

