apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-index
data:
  index.html: |
    <!doctype html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Webapp Homework</title>
    </head>
    <body>
      <h1>Hola desde webapp-deployment</h1>
      <p>Env: homework</p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
    env: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        env: homework
    spec:
      containers:
      - name: webapp
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: web-content
        configMap:
          name: webapp-index

